export const LANGUAGES = [
  { code: "af", name: "Afrikaans", native: "Afrikaans", flag: "🇿🇦" },
  { code: "am", name: "Amharic", native: "አማርኛ", flag: "🇪🇹" },
  { code: "ar", name: "Arabic", native: "العربية", flag: "🇸🇦" },
  { code: "bg", name: "Bulgarian", native: "Български", flag: "🇧🇬" },
  { code: "cs", name: "Czech", native: "Čeština", flag: "🇨🇿" },
  { code: "da", name: "Danish", native: "Dansk", flag: "🇩🇰" },
  { code: "de", name: "German", native: "Deutsch", flag: "🇩🇪" },
  { code: "el", name: "Greek", native: "Ελληνικά", flag: "🇬🇷" },
  { code: "es", name: "Spanish", native: "Español", flag: "🇪🇸" },
  { code: "et", name: "Estonian", native: "Eesti", flag: "🇪🇪" },
  { code: "fi", name: "Finnish", native: "Suomi", flag: "🇫🇮" },
  { code: "fr", name: "French", native: "Français", flag: "🇫🇷" },
  { code: "hr", name: "Croatian", native: "Hrvatski", flag: "🇭🇷" },
  { code: "hu", name: "Hungarian", native: "Magyar", flag: "🇭🇺" },
  { code: "ig", name: "Igbo", native: "Igbo", flag: "🇳🇬" },
  { code: "it", name: "Italian", native: "Italiano", flag: "🇮🇹" },
  { code: "kk", name: "Kazakh", native: "Қазақ", flag: "🇰🇿" },
  { code: "ku", name: "Kurdish", native: "Kurdî", flag: "🇹🇷" }, // Use custom image if you prefer
  { code: "lt", name: "Lithuanian", native: "Lietuvių", flag: "🇱🇹" },
  { code: "lv", name: "Latvian", native: "Latviešu", flag: "🇱🇻" },
  { code: "mg", name: "Malagasy", native: "Malagasy", flag: "🇲🇬" },
  { code: "nl", name: "Dutch", native: "Nederlands", flag: "🇳🇱" },
  { code: "ny", name: "Nyanja", native: "ChiChewa", flag: "🇲🇼" },
  { code: "pl", name: "Polish", native: "Polski", flag: "🇵🇱" },
  { code: "ps", name: "Pashto", native: "پښتو", flag: "🇦🇫" },
  { code: "pt", name: "Portuguese", native: "Português", flag: "🇵🇹" },
  { code: "ro", name: "Romanian", native: "Română", flag: "🇷🇴" },
  { code: "sk", name: "Slovak", native: "Slovenčina", flag: "🇸🇰" },
  { code: "sl", name: "Slovenian", native: "Slovenščina", flag: "🇸🇮" },
  { code: "sn", name: "Shona", native: "chiShona", flag: "🇿🇼" },
  { code: "so", name: "Somali", native: "Soomaali", flag: "🇸🇴" },
  { code: "st", name: "Sesotho", native: "Sesotho", flag: "🇱🇸" },
  { code: "sw", name: "Swahili", native: "Kiswahili", flag: "🇰🇪" },
  { code: "tn", name: "Tswana", native: "Setswana", flag: "🇧🇼" },
  { code: "tr", name: "Turkish", native: "Türkçe", flag: "🇹🇷" },
  { code: "uz", name: "Uzbek", native: "Oʻzbek", flag: "🇺🇿" },
  { code: "wo", name: "Wolof", native: "Wolof", flag: "🇸🇳" },
  { code: "xh", name: "Xhosa", native: "isiXhosa", flag: "🇿🇦" },
  { code: "yo", name: "Yoruba", native: "Yorùbá", flag: "🇳🇬" },
  { code: "zh", name: "Chinese", native: "中文", flag: "🇨🇳" }
];
